version: '2'

volumes: 
   nextcloud: 
   config: 

services:
  app:
    image: nextcloud
    build:
      context: .
    ports: 
      - 8080:80
    restart: no
    volumes:
      - nextcloud:/var/www/html 
      - config:/var/www/html/config
      - ${GITPOD_REPO_ROOT}:/var/www/html/custom_apps/geoblocker
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=test123 
      - NEXTCLOUD_TRUSTED_DOMAINS=*.gitpod.io 
      - OVERWRITEPROTOCOL=https