version: '2'

services:
  app:
    build: .
    ports: 
      - 8080:80
    restart: no
    volumes:
      - ${GITPOD_REPO_ROOT}:/var/www/html/custom_apps/geoblocker
    environment:
      - SQLITE_DATABASE=nc
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=test123 
      - NEXTCLOUD_TRUSTED_DOMAINS=*.gitpod.io 
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES=192.168.0.0/16