
name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Markdown Linting Action
      uses: avto-dev/markdown-lint@v1.3.1
      with:
        config: /.github/lint/markdown-lint.yml
        args: '*.md'
