name: PHPUnit Tests

on:
  workflow_dispatch:

jobs:
  php:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP: Nextcloud ${{ matrix.nextcloud }} - PHP ${{ matrix.php-versions }} - DB ${{ matrix.database }}"
    strategy:
      matrix:
        php-versions: ['7.4']
        nextcloud: ['stable20']
        database: ['sqlite']
        experimental: [false]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_sqlite,pdo_mysql,pdo_pgsql,gd,zip
          coverage: pcov
          
      - name: Set up server non MySQL
        uses: SMillerDev/nextcloud-actions/setup-nextcloud@main
        with:
          cron: true
          version: ${{ matrix.nextcloud }}
          database-type: ${{ matrix.database }}

      - name: Prime app build
        run: make

      - name: Configure server with app
        uses: SMillerDev/nextcloud-actions/setup-nextcloud-app@main
        with:
          app: 'geoblocker'
          #check-code: true
          check-code: false

#      - name: Setup problem matchers for PHPUnit
#        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
#
      - name: Prep Maxmind
        run: sudo apt-get update && sudo apt-get install geoipupdate && echo "${{ secrets.GEOIP_CONF }}" > /etc/GeoIP.conf && geoipupdate

      - name: Prep PHP tests
        working-directory: ../server/apps/geoblocker
        run: make prepare-test
        
      - name: Unit-Tests
        working-directory: ../server/apps/geoblocker
        run: make unit-test
#        
#      - name: Upload codecoverage
#        working-directory: ../server/apps/news
#        run: bash <(curl -s https://codecov.io/bash) -f build/php-unit.clover -N ${{ github.sha }}

      - name: Clean up
        run: rm /etc/GeoIP.conf
