name: PHPUnit Tests

on:
  workflow_dispatch:
  
env:
  POSTGRES_PASSWORD: nc_test_db
  MYSQL_USER: nc_test
  MYSQL_PASSWORD: nc_test_db
  MYSQL_DATABASE: nc_test
  MYSQL_PORT: 3800

jobs:
  php:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP: Nextcloud ${{ matrix.nextcloud }} - PHP ${{ matrix.php-versions }} - DB ${{ matrix.database }}"
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']
        nextcloud: ['stable21', 'stable22', 'stable23']
        database: ['sqlite', 'pgsql', 'mysql
        experimental: [false]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pdo_sqlite,pdo_mysql,pdo_pgsql,gd,zip
          coverage: pcov
          
      #- name: Set up server non MySQL
      #  uses: SMillerDev/nextcloud-actions/setup-nextcloud@main
      #  with:
      #    cron: true
      #    version: ${{ matrix.nextcloud }}
      #    database-type: ${{ matrix.database }}
          
      ### MySQL specific setup
      - name: Setup mysql
        if: matrix.database == 'mysql'
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: '10.5'
          host port: ${{ env.MYSQL_PORT }}
          mysql database: ${{ env.MYSQL_DATABASE }}
          mysql root password: ${{ env.MYSQL_PASSWORD }}
          mysql user: ${{ env.MYSQL_USER }}
          mysql password: ${{ env.MYSQL_PASSWORD }}

      - name: Set up server MySQL
        if: matrix.database == 'mysql'
        uses: SMillerDev/nextcloud-actions/setup-nextcloud@main
        with:
          version: ${{ matrix.nextcloud }}
          cron: true
          database-type: ${{ matrix.database }}
          database-host: 127.0.0.1
          database-port: ${{ env.MYSQL_PORT }}
          database-name: ${{ env.MYSQL_DATABASE }}
          database-user: root
          database-password: ${{ env.MYSQL_PASSWORD }}

      ### Back to normal setup
      - name: Set up server non MySQL
        if: matrix.database != 'mysql'
        uses: SMillerDev/nextcloud-actions/setup-nextcloud@main
        with:
          version: ${{ matrix.nextcloud }}
          cron: true
          database-type: ${{ matrix.database }}
          database-host: localhost
          database-port: 5432
          database-name: postgres
          database-user: postgres
          database-password: ${{ env.POSTGRES_PASSWORD }}

      - name: Prime app build
        run: make

      - name: Configure server with app
        uses: SMillerDev/nextcloud-actions/setup-nextcloud-app@main
        with:
          app: 'geoblocker'
          #check-code: true
          check-code: false

#      - name: Setup problem matchers for PHPUnit
#        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
#
      - name: Prep Maxmind
        run: sudo apt-get update 
          && sudo apt-get install geoipupdate 
          && sudo mv GeoIP.template.conf /etc/GeoIP.conf 
          && sudo sed -i "s/<<ID>>/${{ secrets.MM_ID }}/g" /etc/GeoIP.conf
          && sudo sed -i "s/<<KEY>>/${{ secrets.MM_KEY }}/g" /etc/GeoIP.conf
          && sudo geoipupdate

      - name: Prep PHP tests
        working-directory: ../server/apps/geoblocker
        run: make prepare-test
        
      - name: Unit-Tests
        working-directory: ../server/apps/geoblocker
        run: make unit-test
#        
#      - name: Upload codecoverage
#        working-directory: ../server/apps/news
#        run: bash <(curl -s https://codecov.io/bash) -f build/php-unit.clover -N ${{ github.sha }}

      - name: Clean up
        run: sudo rm /etc/GeoIP.conf
